analytics: {}
color:
  brandColors:
    - '#181F2F'
    - '#D7D8D0'
    - '#47648E'
    - '#FDA25C'
    - '#86939C'
  brandStrength: 0.1875
  lightness: 0.25
  rhythmicContrast: 0
  saturation: 0.452302
cta: {}
layout_spectrum: 0.631578
name: Sonic Space
opengraph: {}
purpose: []
typography_spectrum: 0.712171
coverPrefs:
  filter: false
