name: Sonic Space
favicon: null
layout_spectrum: 0.8952
typography_spectrum: 0.67555
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#f40000'
    - '#f67701'
    - '#653353'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
