name: Sonic Space
favicon: null
layout_spectrum: 0.8952
typography_spectrum: 0.777903180103749
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#f40000'
    - '#f67701'
    - '#653353'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
