name: Sonic Space
favicon: null
layout_spectrum: 0.27509269514121115
typography_spectrum: 0.777903180103749
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5167043770197779
  lightness: 0.750189695507288
  saturation: 0.2399561193305999
  rhythmicContrast: 0.7142532493453473
purpose: []
